<?php
set_include_path(dirname(__FILE__).'/../'.PATH_SEPARATOR.get_include_path());
require_once 'config.php';
require_once 'Monnix.class.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-04 at 14:57:55.
 */
class MonnixTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Monnix
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Monnix;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monnix::getAlert
     * @todo   Implement testGetAlert().
     */
    public function testGetAlert()
    {
        $result = $this->object->getAlert();
        $this->assertNotNull($result);
    }

    /**
     * @covers Monnix::getGraph
     * @todo   Implement testGetGraph().
     */
    public function testGetGraph()
    {
    	$result = $this->object->getGraph();
    	$this->assertNotNull($result);
    }
}
